#!/usr/bin/env ansible-playbook

- name: WORKSTATION
  gather_facts: yes
  hosts: workstation
  become: true

  roles:
  - role: fedora-workstation

  tasks:
  - debug: var=ansible_version
  - command: id
  - meta: end_play
   
