---
# install packages for distro

- name: distro_pkg.yml | install from list
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - vim
    - neovim
    - tmux
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm

- name: distro_pkg.yml | upgrade all
  dnf:
    name: "*"
    state: latest

- name: distro_pkg.yml | remove no longer required
  dnf:
    autoremove: yes

